### PR TITLE
 DIscord.py

### PR DESCRIPTION
**Pull request by coolcoy12**
[discord.py-master.zip](https://github.com/ColdGrub1384/LibTerm-Packages/files/3746894/discord.py-master.zip)

### CODE REVIEW

**Comment by ColdGrub1384** [comment]
This is a library. This repo should only contain commands

**Comment by coolcoy12** [comment]
Ok

**Comment by coolcoy12** [comment]
Isn’t there any way to convert/ install custom ones?

**Comment by dullbananas** [comment]
```
python -m pip install -t directory_path extension_name
```

`directory_path` is the path where you want to install it

**Comment by dullbananas** [comment]
This pull request should be closed

**Pull request closed without merging**
