### PR TITLE
Netscan tool for scanning network

### PR DESCRIPTION
**Pull request by andreaponza**
Tool for scan network on specific port and ip address range

### CODE REVIEW

**Comment by Juniar-II** [comment]
Hi, I got a copy of LibTerm for IPad and I was interested in installing third party frameworks such as NPM, Javascript and Nodejs to LibTerm. However, how do you install this applications to LibTerm and how do you access the LibTerm root directory where the Libraries are located. Also how do you get read and write permission.

**Comment by loot-king** [comment]
👌

**Comment by ColdGrub1384** [comment]
@Juniar-II iOS is sandboxed and you can't install binaries. Just Python scripts. Commands are in the app bundle as libraries. You also can't read and write in the iOS root because it's sandboxed.

**Comment by Juniar-II** [comment]
Hi, Ok, So can I Pull the Request and then add an editor such as ivim to already existing packages.
Also I was going to invoke LibTerm command; package list, package install.

**Comment by ColdGrub1384** [comment]
@Juniar-II iVim is written in C and would not work on LibTerm. Only Python programs can be submitted

**Review by Gitter0070 — COMMENTED** [review]
Good

**Comment by Lexxi6969** [comment]
```
``````
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by nikebuttbraxton — COMMENTED** [review]
Governor Booty Hole Here Assimilates Jew And Gentiles Online Soon.

**Pull request merged**
